### ISSUE TITLE
[REQUEST] Warper Origin

### ISSUE THREAD

**Issue by Delt4knight** [Clark919/Origination-Modpack#15]
**What feature would you like to see in the Origination modpack?**
A clear and concise description of what feature you would like me to look into adding.

Replacement Warper origin that actually works and doesn't bug out (This one is complex and cool)

**Relevant links to mods, or directions to where to find the feature you want me to add.**

https://www.curseforge.com/minecraft/mc-mods/mrplagues-warper-origin

**Comment by Clark919** [comment]
Thanks for the submission. As I understand it, this origin adds the ability to travel between dimensions. I'm likely not going to add it due to that factor, as it seems somewhat issue and lag prone for some servers, and I would prefer origins to not be so problematic or have inherently "strong" powers that severely change normal progression.

**Comment by Clark919** [comment]
I have decided not to include this origin due to the conditions mentioned previously. Closing this feature request.
