### ISSUE TITLE
[I/Q] Adapted Origins keeps crashing

### ISSUE THREAD

**Issue by teliria** [Clark919/Origination-Modpack#5]
I originally thought that it was conflicting with my other mods, but it still won't run after only using 4 mods: Adapted Origins, Origins, Fabric API, and Pekhui
I've tried 1.19.3-2.2.0 and 2.1.0
[crash-2023-02-25_03.26.57-client.txt](https://github.com/Clark919/Origination-Modpack/files/10828178/crash-2023-02-25_03.26.57-client.txt)

**Comment by Clark919** [comment]
Any crash message or error report? Or does it just close to desktop?

**Comment by Clark919** [comment]
I can see that the issue is caused by one of the blocks in the mod, I'll try and recreate your issue in 1.19.3 when I can.

**Comment by Clark919** [comment]
Due to a busy schedule, both with personal life and developing this modpack when I have the time, I will only be developing for 1.19.2 for the time being, as it is the most played version. I may update to later versions as time goes on, but odds are I won't be seeking to update until 1.20. For the time being, I recommend using the 1.19.2 versions of your mods with Adapted Origins. Cheers.
